[package]
name = "rust_calculate"
version = "0.1.0"
authors = ["hh1718"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.4.0"
rand = "0.6.0"
